version: "3.8"
services: 
  client: 
    build: ./src/client
    ports:
      - 5173:5173
  server:
    build: ./src/server
    ports:
      - 4000:4000
    environment: 
       AWS_ACCESS_KEY_ID: 
       AWS_SECRET_ACCESS_KEY: 
       AWS_SESSION_TOKEN: 
       FLICKR_API_KEY: 